version: "3.8"

services:
  flo-interviewer-backend:
    build: .
    container_name: flo-interviewer-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Persist logs, uploads, and interview data
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./interview_data:/app/interview_data
      - ./user_uploads:/app/user_uploads
      - ./transcriptions:/app/transcriptions
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - flo-interviewer-network

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: flo-interviewer-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - flo-interviewer-backend
  #   networks:
  #     - flo-interviewer-network

  # Optional: Add a database service
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: flo-interviewer-db
  #   environment:
  #     POSTGRES_DB: interview_analysis
  #     POSTGRES_USER: interview_user
  #     POSTGRES_PASSWORD: secure_password_change_this
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - flo-interviewer-network

networks:
  flo-interviewer-network:
    driver: bridge
# volumes:
#   postgres_data:
